### ISSUE TITLE
Hostname resolving error when connecting with Supabase Postgresql database

### ISSUE THREAD

**Issue by AbdullahUsmani** [stepzen-samples/stepzen-api-workshop#1]
I have set up Stepzen as described in the [Getting Started Docs](https://stepzen.com/docs/quick-start/with-database-postgresql). I get the following error when running `stepzen start`: 

```
{
  "data": {
    "getProfilesList": null
  },
  "errors": [
    {
      "message": "database error: can't prepare the statement for execution failed to connect to `host=postgres user=root database=`: hostname resolving error (lookup postgres on 10.97.0.10:53: no such host)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getProfilesList"
      ]
    }
  ]
}
```

The message shows wrong hostname, user and empty database, although my config file has the correct credentials: 

```
configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://postgres:[My Password]@[My Supabase DB Host]/postgres
```

I have also tried to connect to the DB directly from a client and the connection is working fine. 
Can someone help why this issue is coming up when trying to connect from Supabase Graphiql explorer running on localhost?

Thanks,
